export const seedShops = [
  { id: 'shop-1', name: 'Sede Mario Quintana', address: 'Estrada Martín Félix Berta 2392', is_active: true },
  { id: 'shop-2', name: 'Sede Costa e Silva', address: 'Av. Dante Ângelo Pilla 206', is_active: true },
];
export const seedBarbers = [
  {
    id: 'barber-1',
    shop_id: 'shop-1',
    name: 'Michael Rozo',
    bio: 'Mestre em degradê e barboterapia.',
    photo_url: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?ixlib=rb-4.0.3&auto=format&fit=crop&w=256&q=80',
    initials: 'MR',
    color: '#FCD116',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'barber-2',
    shop_id: 'shop-1',
    name: 'René Brito',
    bio: 'Especialista em cortes clássicos e design de barba.',
    photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=256&q=80',
    initials: 'RB',
    color: '#003893',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'barber-3',
    shop_id: 'shop-2',
    name: 'Arley Munhoz',
    bio: 'Especialista em Nano pigmentação de barba.',
    photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3&auto=format&fit=crop&w=256&q=80',
    initials: 'AM',
    color: '#CE1126',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'barber-4',
    shop_id: 'shop-2',
    name: 'Guillerme',
    bio: 'Cortes modernos e tendências. Do degradê ao nevou.',
    photo_url: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?ixlib=rb-4.0.3&auto=format&fit=crop&w=256&q=80',
    initials: 'G',
    color: '#4CAF50',
    is_active: true,
    created_at: new Date().toISOString(),
  },
];
export const seedServices = [
  { id: 'svc-1', name: 'Corte Degradê', description: 'Corte degradê na máquina', price: 35, duration_minutes: 45, is_active: true },
  { id: 'svc-2', name: 'Barba', description: 'Design e modelagem de barba', price: 25, duration_minutes: 30, is_active: true },
  { id: 'svc-3', name: 'Barboterapia', description: 'Ritual completo com toalha quente', price: 35, duration_minutes: 45, is_active: true },
  { id: 'svc-4', name: 'Corte Máquina', description: 'Corte simples na máquina', price: 25, duration_minutes: 30, is_active: true },
  { id: 'svc-5', name: 'Sobrancelhas', description: 'Design e alinhamento', price: 10, duration_minutes: 15, is_active: true },
  { id: 'svc-6', name: 'Limpeza Facial Simples', description: 'Limpeza e hidratação básica', price: 10, duration_minutes: 20, is_active: true },
  { id: 'svc-7', name: 'Limpeza Facial Profunda', description: 'Limpeza completa com extração', price: 40, duration_minutes: 60, is_active: true },
  { id: 'svc-8', name: 'Corte + Barba + Sobrancelhas', description: 'O combo completo do homem moderno', price: 60, duration_minutes: 90, is_active: true },
  { id: 'svc-9', name: 'Corte + Sobrancelhas', description: 'Corte e alinhamento de sobrancelhas', price: 40, duration_minutes: 60, is_active: true },
  { id: 'svc-10', name: 'Barba + Sobrancelhas', description: 'Design de barba e sobrancelhas', price: 30, duration_minutes: 45, is_active: true },
  { id: 'svc-11', name: 'Pigmentação Cabelo', description: 'Coloração para cabelos masculinos', price: 15, duration_minutes: 30, is_active: true },
  { id: 'svc-12', name: 'Pigm Barba', description: 'Coloração e preenchimento de barba', price: 15, duration_minutes: 30, is_active: true },
  { id: 'svc-13', name: 'Pigmentação Cavanhaque', description: 'Coloração localizada no cavanhaque', price: 10, duration_minutes: 15, is_active: true },
  { id: 'svc-14', name: 'Luzes', description: 'Luzes no cabelo masculino', price: 80, duration_minutes: 90, is_active: true },
  { id: 'svc-15', name: 'Nevou', description: 'Platinado global masculino', price: 110, duration_minutes: 120, is_active: true },
  { id: 'svc-16', name: 'Nano pigmentação barba', description: 'Feito exclusivamente pelo barbeiro Arley', price: 250, duration_minutes: 120, is_active: true },
];

// Working hours: 0=Sunday, 1=Monday, ..., 6=Saturday
export const generateWorkingHours = (barberId) => [
  { id: `wh-${barberId}-0`, barber_id: barberId, day_of_week: 0, start_time: null, end_time: null, is_off: true },
  { id: `wh-${barberId}-1`, barber_id: barberId, day_of_week: 1, start_time: '09:00', end_time: '20:00', is_off: false },
  { id: `wh-${barberId}-2`, barber_id: barberId, day_of_week: 2, start_time: '09:00', end_time: '20:00', is_off: false },
  { id: `wh-${barberId}-3`, barber_id: barberId, day_of_week: 3, start_time: '09:00', end_time: '20:00', is_off: false },
  { id: `wh-${barberId}-4`, barber_id: barberId, day_of_week: 4, start_time: '09:00', end_time: '20:00', is_off: false },
  { id: `wh-${barberId}-5`, barber_id: barberId, day_of_week: 5, start_time: '09:00', end_time: '20:00', is_off: false },
  { id: `wh-${barberId}-6`, barber_id: barberId, day_of_week: 6, start_time: '09:00', end_time: '20:00', is_off: false },
];
